name: Release
on:
  push: { tags: "v[0-9]+.[0-9]+.[0-9]+*" }
  workflow_dispatch:
permissions: {}

jobs:
  release:
    uses: nodenv/.github/.github/workflows/release.yml@v5
    permissions: { contents: write, id-token: write }
    secrets: inherit
