name: Sync Default Branch
on:
  push: { branches: $default-branch }
  workflow_dispatch:

# One-time commands for users to switch-over:
# ```console
# git branch -m master main
# git fetch origin
# git branch -u origin/main main
# git remote set-head origin -a
# ```

jobs:
  sync:
    uses: nodenv/.github/.github/workflows/sync-default-branch.yml@v3
