name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@v4
    permissions:
      contents: read
      packages: read
      statuses: write # to report status checks
