name: Test
on: [push, pull_request]

jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@main
    permissions:
      contents: read
      packages: read
      statuses: write # to report status checks
