name: Test
on:
  pull_request:
  push:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:
permissions: {}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with: { npm: false }
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  super-lint:
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - actions
          - homebrew-nodenv
          - jetbrains-npm
          # - node-build
          - node-build-prerelease
          - node-build-update-defs
          # - nodenv
          # - nodenv-aliases
          - nodenv-default-packages
          - nodenv-each
          - nodenv-env
          - nodenv-installer
          - nodenv-man
          - nodenv-npm-migrate
          - nodenv-nvmrc
          # - nodenv-package-json-engine
          - nodenv-package-rehash
          # - nodenv-update
          - nodenv-vars
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: nodenv/${{ matrix.repo }}
          persist-credentials: false
      - uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          USE_FIND_ALGORITHM: true # workaround superlinter
          ### below here should match our reusable test workflow config
          GITHUB_TOKEN: ${{ github.token }}
          BASH_EXEC_IGNORE_LIBRARIES: true # superlinter bug #5731
          FILTER_REGEX_EXCLUDE: node_modules
          VALIDATE_BIOME_FORMAT: false # conflicts with prettier
          VALIDATE_BIOME_LINT: false # conflicts with prettier
          VALIDATE_GIT_COMMITLINT: false # commitlint is bad
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JSCPD: false # too prone to false-positives
          VALIDATE_SPELL_CODESPELL: false # TODO
