name: Release
on:
  push: { tags: "v*.*.*" }
  workflow_dispatch:
permissions: {}

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with: { homebrew: false, npm_scope: "" }
    permissions: { contents: write }
    secrets: inherit
