name: Test
on:
  pull_request:
  push: {branches: main}
  schedule: [{cron: '0 0 10 * *'}] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:
permissions: {}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with: {npm: false}
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write
