name: Sync Default Branch
on: workflow_call
permissions: {}

jobs:
  default-branch:
    if: github.ref_name == github.event.repository.default_branch
    permissions: { contents: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # need creds for subsequent git ops

      - run: git push --force origin HEAD:refs/heads/master
