name: Sync Default Branch
on: workflow_call
permissions: {}

jobs:
  default-branch:
    if: github.ref_name == github.event.repository.default_branch
    permissions: { contents: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true # need creds for subsequent git ops

      - run: git push --force origin HEAD:refs/heads/master
