name: Sync Default Branch
on: workflow_call
permissions: {}

jobs:
  default-branch:
    if: github.ref_name == github.event.repository.default_branch
    permissions: { contents: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with: { egress-policy: audit }
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true # need creds for subsequent git ops

      - run: git push --force origin HEAD:refs/heads/master
