name: Tag Major Version
on:
  push: { tags: "v*.*.*" }
  workflow_dispatch:
  workflow_call:
permissions: {}

jobs:
  major:
    if: github.ref_type == 'tag' && !contains(github.ref, '-') # skip prereleases
    permissions: {contents: write}
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with: {egress-policy: audit}
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: git push -f origin "HEAD:refs/heads/${GITHUB_REF_NAME%%.*}"
