name: Tag Major Version
on:
  push: { tags: "v*.*.*" }
  workflow_dispatch:
  workflow_call:
permissions: { contents: write }

jobs:
  major:
    if: github.ref_type == 'tag' && !contains(github.ref, '-') # skip prereleases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git push -f origin "HEAD:refs/heads/${GITHUB_REF_NAME%%.*}"
