name: Test
on:
  workflow_call:
    inputs:
      npm:
        description: "Run npm-cit job."
        default: true
        required: false
        type: boolean
      superlinter:
        description: "Run super-linter job."
        default: true
        required: false
        type: boolean

permissions: { contents: read }
jobs:
  npm-test:
    if: inputs.npm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu-latest, macOS-latest] }
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - run: npm cit
        env:
          GITHUB_TOKEN: ${{ github.token }}

  super-lint:
    if: inputs.superlinter
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { fetch-depth: 0, persist-credentials: false }
      # eventually check out .github repo itself to support sharing of config files.
      # not necessary right now since codespell is borked.
      # also, superlinter is behind and doesn't recognize job.workflow_* vars used below
      # - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      #   with:
      #     repository: ${{ job.workflow_repository }}
      #     ref: ${{ job.workflow_sha }}
      #     path: .github/workflows/${{ job.workflow_repository }}
      #     persist-credentials: false
      - uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BASH_EXEC_IGNORE_LIBRARIES: true # superlinter bug
          FILTER_REGEX_EXCLUDE: node_modules
          VALIDATE_BIOME_FORMAT: false # conflicts with prettier
          VALIDATE_BIOME_LINT: false # conflicts with prettier
          VALIDATE_GIT_COMMITLINT: false # commitlint is bad
          VALIDATE_JSCPD: false # too prone to false-positives
          VALIDATE_SPELL_CODESPELL: false # too many false-positives

  dependency-review:
    if: startsWith('pull_request', github.event_name)
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.securityscorecards.dev:443
            github.com:443
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0

  ossf-scorecard:
    if: github.ref_name == github.event.repository.default_branch
    permissions: { id-token: write, security-events: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: ossf-scorecard-results.sarif
          results_format: sarif
          publish_results: true
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ossf-scorecard-results.sarif
          path: ossf-scorecard-results.sarif
      - uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: ossf-scorecard-results.sarif
